### ISSUE TITLE
Complain missing shared libraries: libXpm.so.4 upon adding cartridge openshift-cartridge-php

### ISSUE THREAD

**Issue by jimmychu0807** [boekkooi/openshift-cartridge-php#1]
Thanks for the work on creating updated nginx/php cartridges.

I am running my own openshift-origin in my own server, and added your two cartridges, Nginx, and the php to the system with `oo-admin-cartridge` on node and `oo-admin-ctl-cartridge` on broker.

I `rhc app create` an nginx app, it works fine. Then I add this php cartridge and it complains 

```
$ rhc cartridge add cust-php-5.6.6 -a nginxphp01 $CONNECT_CFG
Adding cust-php-5.6.6 to application 'nginxphp01' ... ~/php/usr/php-5.6.6/bin ~/php
php: error while loading shared libraries: libXpm.so.4: cannot open shared object file: No such file or directory
php: error while loading shared libraries: libXpm.so.4: cannot open shared object file: No such file or directory
```

I appreciate if you could shed me any light on what to do to fix it. Thanks.

**Comment by boekkooi** [comment]
Ok so the reason for the error is that the cartridge binaries where build on openshift online.
As I see it you have a couple of options:
1. Fork this repo and follow the [compiling a new version](https://github.com/boekkooi/openshift-cartridge-php) instructions in the readme. (Be sure you compile on your openshift-origin server)
2. Try to install all required/missing libs (welcome to the linux version of dll hell)
3. Fork [`openshift-origin-cartridge-php`](https://github.com/openshift/origin-server/tree/master/cartridges/openshift-origin-cartridge-php) and customize it to support PHP 5.5 & 5.6

I think that option 1 would be the one I would use.  I hope this helps let me know if you experience any problems or with you have any more questions.

**Comment by jimmychu0807** [comment]
Hi, thanks for the help.

Finally I am able to run your cartridge :smile: . The error didn't happen the second time I run... don't know why.

But I hit another issue that on `install` script. This line,

``` BASH
...
php -r "readfile('https://getcomposer.org/installer');" | php
...
```

actually download and install composer on `${OPENSHIFT_PHP_DIR}/usr/php-${PHP_VERSION}`, but `${OPENSHIFT_PHP_DIR}/usr/` is a symlink to `.cartridge_repository/<oo-cartridge-php>/0.0.1/usr`, the cartridge repository itself, and thus non-writable. I change it to `${OPENSHIFT_PHP_DIR}/bin`.

I guess this probably only happen in origin server...

Anyway, thanks for your work. Building custom cartridge in openshift is a nightmare...

**Comment by boekkooi** [comment]
No problem glad it worked out for you!

Yeah that sounds like a origin problem but it should be fixed since it will also give problems when installing pecl extensions. 
I have looked at moving the extension for installing pecl packages and it should be possible soon in the repo. I will also change the composer installation and ~/.composer as a writable file in the install.
