### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by lucho2d7** [boekkooi/openshift-cartridge-php#12]
Hi boekkooi.
In this paragraph of the readme:
_"In the fpm directory create the php.ini.erb file and copy the content from conf/php-fpm.ini.erb into it. Also create the php-fpm.conf.erb file and copy the content from **conf/php-fpm.ini.erb** into it. Now you can customize the php-fpm configuration."_

I think it should read _"Also create the php-fpm.conf.erb file and copy the content from **conf/php-fpm.conf.erb** into it."_ The link is correct though.

Regards

**Comment by boekkooi** [comment]
Hi @lucho2d7,
Could you please create a PR for this and I will merge it. 
Thank you :smile:

**Comment by lucho2d7** [comment]
Done! You are welcome.
