### ISSUE TITLE
php pecl extension dynamic declaration overwritten when having custom ini files

### ISSUE THREAD

**Issue by lucho2d7** [boekkooi/openshift-cartridge-php#15]
Having the following custom files
.openshift/fpm/php.ini.erb
.openshift/cli/php.ini.erb

If i declare an extension in php-pecl.txt (in this case mongodb), it does get installed when pushing to the openshift online repository, but the declaration meant to be done by bin/install_pecl/install_pecl() function vanishes.

From the push log I can see that the lib/util/config() function is called at the very start of the build process, and 2 more times:

remote: - php-fpm.ini: /var/lib/openshift/someId/app-root/runtime/repo//.openshift/fpm/php.ini.erb
remote: - php-fpm.conf: No change
remote: - php.ini: /var/lib/openshift/someId/app-root/runtime/repo//.openshift/cli/php.ini.erb
remote: PHP pecl mongodb not installed or old version.
[...]
remote: Downloading mongodb-1.1.2.tgz:
**[...mongodb is built...]**
remote: Installing shared extensions:     /var/lib/openshift/someId/php//ext/
remote: Cleaning build directory.
[...here the "extension=mongodb.so" string is correctly appended to the ini files...]
**[...composer install executes...]**
remote: Generating optimized class loader
remote: Compiling common classes
remote: Preparing build for deployment
remote: Deployment id is someId
remote: Activating deployment
remote: CLIENT_MESSAGE: Starting MongoDB...
remote: CLIENT_RESULT: MongoDB started.
remote: Checking configuration
remote: - php-fpm.ini: /var/lib/openshift/someId/app-root/runtime/repo//.openshift/fpm/php.ini.erb
remote: - php-fpm.conf: No change
remote: - php.ini: /var/lib/openshift/someId/app-root/runtime/repo//.openshift/cli/php.ini.erb
**[...here config() is executed again so the appended string is lost and the newly installed extension remains not declared triggering the install with every push...]**
remote: PHP-FPM instance is stopped
remote: PHP-FPM already stopped
remote: PHP-FPM instance is started
remote: Setting environment variables...
remote: Mongo Host set to somehost
remote: Mongo Port set to someport
remote: Database driver set to 'mongodb'...
remote: Migrating storage and log directories...
remote: Checking configuration
remote: - php-fpm.ini: No change
remote: - php-fpm.conf: No change
remote: - php.ini: No change
**[..again config() seems to be executed for the 3rd time...]**
remote: PHP-FPM already running
remote: Nginx instance is started
remote: Failed to report deployment to broker with status 503.  This will be corrected on the next git push.
remote: -------------------------
remote: Git Post-Receive Result: success
remote: Activation status: success
remote: Deployment completed with status: success

I don't know why the config() function is called 3 times. Should it be?

Note that I do not have the 
${OPENSHIFT_PHP_DIR}/bin/control build
line in my build hook because I do not find it necessary as it is anyway executed.

**Comment by boekkooi** [comment]
Hi @lucho2d7, 

Did you try adding `extension=mongodb.so` to your `.openshift/cli/php.ini.erb`?
(Another option would be to add `export PHP_INI_SCAN_DIR`)

**Comment by lucho2d7** [comment]
Hi @boekkooi,
Yes, I certainly did try that workaround and It works. I just wanted to warn you about this issue and understand why that config() function is called 3 times. I will edit the readme adding this note to avoid a headache to anyone that runs into this in the future. Thanks.

**Comment by boekkooi** [comment]
Ok this issue should be fixed now because [`PHP_INI_SCAN_DIR`](https://github.com/boekkooi/openshift-cartridge-php/blob/master/env/PHP_INI_SCAN_DIR.erb) is now set and all extensions configs are into [`conf/ext/`](https://github.com/boekkooi/openshift-cartridge-php/blob/master/bin/install_pecl#L85)
