### ISSUE TITLE
Cannot install Phalcon version 2.0.+

### ISSUE THREAD

**Issue by soneldrian** [boekkooi/openshift-cartridge-php#17]
I have been trying to install Phalcon version 2.0.9 and 2.0.10, but everytime it hangs on "make"
I tried to compile via SSH, but it didn't work too.
It seems to be related with php-config dirs and the Phalcon compilation config files.
Could you please check this out for us? Thank you very much!

**Comment by soneldrian** [comment]
This is the error:

`remote: Compiling Phalcon.
remote: /bin/sh /tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits/libtool --mode=compile cc  -I. -I/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits -DPHP_ATOM_INC -I/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits/include -I/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits/main -I/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/main -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/TSRM -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/Zend -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/ext -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits/phalcon.zep.c -o phalcon.lo 
remote: mkdir .libs
remote:  cc -I. -I/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits -DPHP_ATOM_INC -I/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits/include -I/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits/main -I/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/main -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/TSRM -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/Zend -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/ext -I/var/lib/openshift/56ccf33d7628e1f7b3000212/php//usr/php-5.6.16/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
Connection to yulia2-radhi.rhcloud.com closed by remote host.
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer`

**Comment by boekkooi** [comment]
You could try adding `export CFLAGS="-O2 --fvisibility=hidden"` after https://github.com/boekkooi/openshift-cartridge-php/blob/7b6521119d04322528d20fa3567d6cea386412bb/bin/install_pecl#L43,

It looks like that is what is missing according to [phalcon docs](https://docs.phalconphp.com/en/latest/reference/install.html#compilation)

**Comment by max-kuzmin** [comment]
Don't work:

`Building git ref 'master', commit 31293f7`
`Checking configuration`
`- php-fpm.ini: No change`
`- php-fpm.conf: No change`
`- php.ini: No change`
`PHP pecl phalcon not installed or old version .`
`/tmp/pecl-build /var/lib/openshift/56d0657a7628e12f0e00013a/nginx`
`Downloading phalcon-v2.0.10.tar.gz:`
`- skipping file exists.`
`Unpacking phalcon-v2.0.10.tar.gz:`
`- skipping directory exists.`
`/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits /tmp/pecl-build /var/lib/openshift/56d0657a7628e12f0e00013a/nginx`
`Configuring phalcon.`
`Configuring for:`
`PHP Api Version: 20131106`
`Zend Module Api No: 20131226`
`Zend Extension Api No: 220131226`
`checking for grep that handles long lines and -e... /bin/grep`
`checking for egrep... /bin/grep -E`
`checking for a sed that does not truncate output... /bin/sed`
`checking for cc... cc`
`checking for C compiler default output file name...`
`configure: error: in '/tmp/pecl-build/cphalcon-phalcon-v2.0.10/build/64bits':`
`configure: error: C compiler cannot create executables`
`See 'config.log' for more details.`
`An error occurred executing 'gear build' (exit code: 77)`
`Error message: CLIENT_ERROR: Failed to execute: 'control build' for /var/lib/openshift/56d0657a7628e12f0e00013a/nginx`
`/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-node-1.38.6/lib/openshift-origin-node/model/v2_cart_model.rb:1387:in 'block in do_control_with_directory'`
`/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-node-1.38.6/lib/openshift-origin-node/model/v2_cart_model.rb:1175:in 'process_cartridges'`
`/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-node-1.38.6/lib/openshift-origin-node/model/v2_cart_model.rb:1350:in 'do_control_with_directory'`
`/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-node-1.38.6/lib/openshift-origin-node/model/v2_cart_model.rb:1197:in 'do_control'`
`/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-node-1.38.6/lib/openshift-origin-node/model/application_container_ext/cartridge_actions.rb:586:in 'build'`
`/usr/bin/gear:290:in 'block (3 levels) in <main>'`
`/usr/bin/gear:75:in 'do_command'`
`/usr/bin/gear:242:in 'block (2 levels) in <main>'`
`/opt/rh/ruby193/root/usr/share/gems/gems/commander-4.0.3/lib/commander/command.rb:180:in 'call'`
`/opt/rh/ruby193/root/usr/share/gems/gems/commander-4.0.3/lib/commander/command.rb:180:in 'call'`
`/opt/rh/ruby193/root/usr/share/gems/gems/commander-4.0.3/lib/commander/command.rb:155:in 'run'`
`/opt/rh/ruby193/root/usr/share/gems/gems/commander-4.0.3/lib/commander/runner.rb:385:in 'run_active_command'`
`/opt/rh/ruby193/root/usr/share/gems/gems/commander-4.0.3/lib/commander/runner.rb:74:in 'run!'`
`/opt/rh/ruby193/root/usr/share/gems/gems/commander-4.0.3/lib/commander/delegates.rb:11:in 'run!'`
`/opt/rh/ruby193/root/usr/share/gems/gems/commander-4.0.3/lib/commander/import.rb:10:in 'block in <top (required)>'`

**Comment by boekkooi** [comment]
Ok so I create a test branch and the major problem seems to be that the phalcon build time is taking to long.

You can try it yourself using `rhc cartridge add --timeout 3600 -a myapp http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php?commit=144995b69296889a14f94de96feb81c810e3e25b`

**Comment by boekkooi** [comment]
Ok so I will the main problem is the openshift timeout system in combination with phalcon.
When compiling phalcon it will show one line `-DPIC -o .libs/phalcon.o` and create no more output... this will make openshift close the connection and fail the build. I have no clue on how to fix this.

**Comment by boekkooi** [comment]
Ok so phalcon install should work now but be aware that a medium gear is required to compile phalcon 2.x
