### ISSUE TITLE
Failed to execute: 'control start'

### ISSUE THREAD

**Issue by MiguelRex** [boekkooi/openshift-cartridge-php#18]
Hello i was trying to add your cartridge but I'm getting the next error:

rhc cartridge add -a myapp http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
The cartridge 'http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php' will be
downloaded and installed
Adding http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php to application
'myapp' ...
Checking configuration
- php-fpm.ini: No change
- php-fpm.conf: No change
- php.ini: No change
  Failed to execute: 'control start' for /var/lib/openshift/myuser/php
  [29-Feb-2016 17:50:12] ERROR: [/var/lib/openshift/myuser/php//conf/php-fpm.conf:521] empty
  value
  [29-Feb-2016 17:50:12] ERROR: failed to load configuration file
  '/var/lib/openshift/myuser/php//conf/php-fpm.conf'
  [29-Feb-2016 17:50:12] ERROR: FPM initialization failed

do you have any clue? I cannot find any solution.

Regards
Miguel Resendiz.

**Comment by MiguelRex** [comment]
P.S. I'm using your NGINX cartridge

**Comment by boekkooi** [comment]
Please try again it should be fixed now

**Comment by MiguelRex** [comment]
Great, Thanks to solve it.
