### ISSUE TITLE
[origin] Don't install in usr/

### ISSUE THREAD

**Issue by boekkooi** [boekkooi/openshift-cartridge-php#2]
Composer install throws a exception since it tries to write to `usr/` also [`COMPOSER_HOME`](https://getcomposer.org/doc/03-cli.md#composer-home) needs to be set

```
...
php -r "readfile('https://getcomposer.org/installer');" | php
...
```

Pecl install also fails because it will write to `usr/`

This is related to #1.

**Comment by boekkooi** [comment]
@jimmychu0807 You may want to update and compile based on the last commit 759a318b8738bfae1538e816ebce026147ebf8a1 This should fix all origin issues.

**Comment by jimmychu0807** [comment]
Thank you! Will check it out.
