### ISSUE TITLE
It looks like --env vars is not functioning correctly

### ISSUE THREAD

**Issue by sabrio** [boekkooi/openshift-cartridge-php#20]
Even I set the --env  OPENSHIFT_NGINX_VERSION=1.8.0
`rhc create-app myapp --env OPENSHIFT_NGINX_VERSION=1.8.0 http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-nginx`
when I open my app from openshift console I see there always the latest version(1.9.12)?
Is this a bug or ...?

The same thing is happening here with php cartridge:
 `rhc cartridge add -a myapp --env OPENSHIFT_PHP_VERSION=5.5.22 http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php`

![untitled](https://cloud.githubusercontent.com/assets/9056128/15142525/bf968ed6-16a5-11e6-93de-23783767d829.png)

**Comment by boekkooi** [comment]
Hi @sabrio,

The version show here is the catridge version which in this case is [hardcoded](https://github.com/boekkooi/openshift-cartridge-php/blob/master/metadata/manifest.yml) it is not the version of the installed PHP or Nginx version.

Please login to your gear using ssh and check the installed versions of the software. Or use [`phpinfo`](http://php.net/manual/en/function.phpinfo.php).

Cheers,
Warnar

**Comment by sabrio** [comment]
@boekkooi thanks for you time&expiation
