### ISSUE TITLE
Removing X-Powered-By Header in PHP

### ISSUE THREAD

**Issue by nttm1010** [boekkooi/openshift-cartridge-php#3]
I am using nginx (version 1.7.10) with php (version 5.6.6). How can I remove X-Powered-By in http header? Don't know why but remove expose_php = "On" to "Off" in file php.ini.erb (path: .openshift/cli/php.ini.erb). I tried using ctl_app stop and ctl_app start for restart my php-fpm but it still showing the header.
![tp-2](https://cloud.githubusercontent.com/assets/11404827/10123242/52dbab2e-6524-11e5-8585-3a11b3211182.jpg)

**Comment by thePanz** [comment]
You should edit the `php.ini.erb` related to the "fpm" section.
I was able to hide such header with no other edits.
