### ISSUE TITLE
Empty "OPENSHIFT_PHP_EXTENSION_DIR" (and OPCache extension)

### ISSUE THREAD

**Issue by thePanz** [boekkooi/openshift-cartridge-php#5]
The "OPENSHIFT_PHP_EXTENSION_DIR" environment variable is always empty, thus enabling the OPCache requires a further effort since the "ext" directory can not referenced by using the ENV setting.

I was abe to solve this issue by adding the following code to my `.openshift/fpm/php.ini.erb`

```
zend_extension = "<%= ENV['OPENSHIFT_PHP_DIR'] %>ext/opcache.so"
opcache.enable=1
```

**Comment by boekkooi** [comment]
Mhh that is strange since `OPENSHIFT_PHP_EXTENSION_DIR` is set in https://github.com/boekkooi/openshift-cartridge-php/blob/7b6521119d04322528d20fa3567d6cea386412bb/bin/setup#L34 

What is the result of `${OPENSHIFT_PHP_VERSION_DIR}/bin/php-config --extension-dir` on the cartridge where this happens?

**Comment by limatheus** [comment]
@thePanz 
This works to you?

zend_extension = "<%= ENV['OPENSHIFT_PHP_DIR'] %>ext/opcache.so"
opcache.enable=1

I put those lines on my .openshift/fpm/php.ini.erb, but don't works to me. =/

**Comment by thePanz** [comment]
@limatheus it's working in my environment. I suggest you to login to your gear and execute: `export | grep PHP` to get all the environment variables (related to PHP) available.

**Comment by limatheus** [comment]
Hi @thePanz 

I'm trying activate opcache for some days and nothing works for me =/
I follow your instruction and put those lines in the end of **.openshift/fpm/php.ini.erb** 

```
zend_extension = "<%= ENV['OPENSHIFT_PHP_EXTENSION_DIR'] %>/opcache.so"
opcache.enable=1
```

Make the push to my gear with no errors, but still don't working.

**Comment by thePanz** [comment]
Please check your configuration: it's `OPENSHIFT_PHP_DIR`:
and you should check your exported `env` variables!

```
zend_extension = "<%= ENV['OPENSHIFT_PHP_DIR'] %>ext/opcache.so"
opcache.enable=1
```
