### ISSUE TITLE
Error Compiling PHP 7.0.0

### ISSUE THREAD

**Issue by vs0uz4** [boekkooi/openshift-cartridge-php#7]
Good evening,

Follow the instructions in README.MD to compile a new version of PHP. My intention was to compile the new version of PHP 7.0.0.

But when I run the scripts in the following sequence:

./libs
**./php**
./libs_package

I'm disconnected from the host of OpenShift, whenever you are compiling PHP. The last lines of code that appear on the screen are:

> /bin/sh /var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/libtool --silent --preserve-dup-deps --mode=compile cc -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/fileinfo/libmagic -Iext/fileinfo/ -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/fileinfo/ -DPHP_ATOM_INC -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/include -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/main -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0 -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/date/lib -I/usr/include/libxml2 -I/usr/X11 -I/usr/include/freetype2 -I/var/lib/openshift/5662d55489f5cf7cb000000e/php//usr/shared/libs/include -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/mbstring/oniguruma -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/mbstring/libmbfl -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/mbstring/libmbfl/mbfl -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/catridge/usr/libs/include -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/sqlite3/libsqlite -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/zip/lib -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/TSRM -I/var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/Zend    -I/usr/include -g -O2 -fvisibility=hidden   -c /var/lib/openshift/5662d55489f5cf7cb000000e/app-root/repo/php/compile/tmp/php-7.0.0/ext/fileinfo/libmagic/apprentice.c -o ext/fileinfo/libmagic/apprentice.lo 
> Connection to hostserv.rhcloud.com closed by remote host.
> Connection to hostserv.rhcloud.com closed.

Does anyone have any idea what might be happening? The latest versions 5.5.30 and 5.6.16 usually compiled without any errors. Only the 7.0.0 version which features a mistake and disconnects me from the server.

**Comment by boekkooi** [comment]
Hey @vs0uz4, 

So I have read that there are some issue with compiling PHP 7 on 512mb of RAM so you maybe running into that issue. (source http://jcutrer.com/howto/linux/how-to-compile-php7-on-ubuntu-14-04)
I personally have not tried compiling PHP 7 but If you get it to work please create a PR :smile: 

Good luck!

**Comment by boekkooi** [comment]
Closing this issue please follow PR #8
